opt_in_rules:
- empty_count
- empty_string
- force_unwrapping

disabled_rules:
- trailing_whitespace
- implicit_getter

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

line_length:
    warning: 300
    error: 500
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 6
    error: 8

type_body_length:
    warning: 300
    error: 500

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 25
    error: 30

colon:
  severity: warning  
    
force_cast: error
force_unwrapping: warning
opening_brace: warning
statement_position:
  severity: warning
return_arrow_whitespace: warning
comma: warning

control_statement: warning
#trailing_whitespace:
#  severity: warning
force_try: warning

reporter: "xcode"

identifier_name:
  min_length:
    warning: 2
    error: 1
